version: '3.8'

services:
  unturned-server:
    image: cm2network/steamcmd:root
    container_name: unturned-dedicated-server
    restart: unless-stopped
    ports:
      - "${SERVER_PORT:-27015}:${SERVER_PORT:-27015}/udp"
      - "${QUERY_PORT:-27016}:${QUERY_PORT:-27016}/udp"
    volumes:
      - unturned-data:/home/steam/unturned-server
      - ./config:/tmp/config:ro
    env_file:
      - .env
    command: >
      bash -c "
        echo 'Starting Unturned Dedicated Server...' &&
        
        # Create steam user if needed and fix ownership
        chown -R steam:steam /home/steam &&
        
        # Install Unturned as steam user
        echo 'Installing/Updating Unturned...' &&
        runuser -u steam -- /home/steam/steamcmd/steamcmd.sh +force_install_dir /home/steam/unturned-server +login anonymous +app_update 1110390 validate +quit &&
        
        # Setup server directory
        echo 'Setting up server configuration...' &&
        runuser -u steam -- mkdir -p /home/steam/unturned-server/Servers/\$SERVER_NAME &&
        
        # Copy config files
        if [ -d /tmp/config ]; then
          runuser -u steam -- cp -r /tmp/config/* /home/steam/unturned-server/Servers/\$SERVER_NAME/ 2>/dev/null || true
        fi &&
        
        # Start server
        echo 'Starting server: '\$SERVER_NAME &&
        cd /home/steam/unturned-server &&
        runuser -u steam -- ./ServerHelper.sh +InternetServer/\$SERVER_NAME
      "
    networks:
      - unturned-network

  # Optional: Web-based server management panel
  unturned-web:
    image: nginx:alpine
    container_name: unturned-web-panel
    restart: unless-stopped
    ports:
      - "${WEB_PORT:-8080}:80"
    volumes:
      - ./web:/usr/share/nginx/html:ro
    depends_on:
      - unturned-server
    networks:
      - unturned-network
    profiles:
      - web

networks:
  unturned-network:
    driver: bridge

volumes:
  unturned-data:
    driver: local